[package]
name = "chip8"
version = "0.1.0"
authors = ["LokiFaun <johannes.schuetz@outlook.com>"]

[dependencies]
rand = "0.3"

[dependencies.sdl2]
version = "0.28"
default-features = false
features = ["gfx"]